FROM php:8.3-cli

WORKDIR /app
COPY . .

RUN apt-get update && apt-get install -y unzip git curl \
    && docker-php-ext-install pcntl

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer install --no-dev --optimize-autoloader

EXPOSE 8080

CMD php artisan reverb:start --host=0.0.0.0 --port=8080
